package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"apollo/graph/model"
	"apollo/internal/contextutil"
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"
)

// CreateGamePick is the resolver for the CreateGamePick field.
func (r *mutationResolver) CreateGamePick(ctx context.Context, input model.NewGamePickInput) (*model.GamePick, error) {
	id := uuid.New()
	userID, ok := contextutil.GetUserIDFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("Unauthorized")
	}

	_, err := r.DB.Exec(ctx, `
		INSERT INTO game_pick (
			id, season_id, week_id, user_id,
			selected_team_name, opponent_team_name,
			spread_selection, spread_result, points_assigned,
			created_at, updated_at
		) VALUES (
			$1, $2, $3, $4, $5, $6, $7, $8, $9, now(), now()
		)
	`, id, input.SeasonID, input.WeekID, userID,
		input.SelectedTeamName, input.OpponentTeamName,
		input.SpreadSelection, input.SpreadResult, input.PointsAssigned)

	if err != nil {
		return nil, fmt.Errorf("failed to create game pick: %w", err)
	}

	return &model.GamePick{
		ID:               id.String(),
		WeekID:           input.WeekID,
		SelectedTeamName: input.SelectedTeamName,
		OpponentTeamName: input.OpponentTeamName,
		SpreadSelection:  input.SpreadSelection,
		SpreadResult:     input.SpreadResult,
		PointsAssigned:   input.PointsAssigned,
		CreatedAt:        time.Now().Format(time.RFC3339),
		UpdatedAt:        time.Now().Format(time.RFC3339),
	}, nil
}

// CreateLeagueSeason is the resolver for the CreateLeagueSeason field.
func (r *mutationResolver) CreateLeagueSeason(ctx context.Context, input model.NewSeasonInput) (*model.Season, error) {
	league_season_id := uuid.New()

	// Get sport season id
	sportSeasonId, err := GetSportSeasonId(ctx, r.DB, input.Sport, int(input.YearStart), int(input.YearEnd))
	if err != nil {
		return nil, err
	}

	_, err = r.DB.Exec(ctx, `
		INSERT INTO league_season (
			id, league_id, sport_season_id, created_at, updated_at
		) VALUES (
			$1, $2, $3, now(), now()
		)
	`, league_season_id, input.LeagueID, sportSeasonId)

	if err != nil {
		return nil, fmt.Errorf("failed to create league season: %w", err)
	}

	return &model.Season{
		ID:        sportSeasonId,
		LeagueID:  input.LeagueID,
		YearStart: input.YearStart,
		YearEnd:   input.YearEnd,
		Sport:     input.Sport,
	}, nil
}

// GetLeagueSeasonsByID is the resolver for the GetLeagueSeasonsById field.
func (r *queryResolver) GetLeagueSeasonsByID(ctx context.Context, leagueID string) ([]*model.Season, error) {
	rows, err := r.DB.Query(ctx, `
        SELECT s.id, s.year_start, s.year_end, s.sport
        FROM season s
        INNER JOIN league l ON s.league_id = l.id
        WHERE l.id = $1`, leagueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var seasons []*model.Season
	for rows.Next() {
		var s model.Season
		if err := rows.Scan(&s.ID, &s.YearStart, &s.YearEnd, &s.Sport); err != nil {
			return nil, err
		}
		seasons = append(seasons, &s)
	}

	if rows.Err() != nil {
		return nil, rows.Err()
	}

	return seasons, nil
}

// GetGamePicksByWeek is the resolver for the GetGamePicksByWeek field.
func (r *queryResolver) GetGamePicksByWeek(ctx context.Context, seasonID string, week int32) ([]*model.GamePick, error) {
	panic("unimplemented")
}

// GetWeeklyNflGameSpreads is the resolver for the GetWeeklyNflGameSpreads field.
func (r *queryResolver) GetWeeklyNflGameSpreads(ctx context.Context) ([]*model.GameOdds, error) {
	// UNCOMMENT WHEN NFL IS READY
	// now := time.Now().UTC()
	// seasonWeekData, err := GetCurrentWeekData(ctx, r.DB, "football", 2025, 2026) // TODO: make these params
	// if err != nil {
	// 	return nil, fmt.Errorf("failed to fetch week id %w", err)
	// }

	// seasonWeekEndAsTime, err := time.Parse(time.RFC3339, seasonWeekData.WeekEnd)
	// if err != nil {
	// 	return nil, fmt.Errorf("error week end time")
	// }

	// // Format RFC3339 for API
	// from := now.Format(time.RFC3339)
	// to := seasonWeekEndAsTime.Format(time.RFC3339)

	// THIS TEST MLB FOR NOW
	now := time.Now().UTC()
	oneDayFromNow := now.Add(24 * time.Hour)

	//Get games from Odds API (returns []Game with Spreads)
	games, err := r.OddsService.GetNFLGames(now.Format(time.RFC3339), oneDayFromNow.Format(time.RFC3339))
	if err != nil {
		return nil, fmt.Errorf("failed to fetch NFL games: %w", err)
	}

	var result []*model.GameOdds

	for _, game := range games {
		commenceTime := game.CommenceTime

		// Selection logic
		isPast := commenceTime.Before(time.Now().UTC())
		within24hrs := commenceTime.Sub(time.Now().UTC()) <= 24*time.Hour

		isSelectable := !isPast && within24hrs

		home := game.Spreads.HomeTeam
		away := game.Spreads.AwayTeam

		result = append(result, &model.GameOdds{
			OddsGameID:   game.ID,
			CommenceTime: commenceTime.Format(time.RFC3339),
			IsSelectable: isSelectable,
			HomeTeam: &model.TeamOddsInfo{
				Name:   home.Name,
				Spread: home.Point,
			},
			AwayTeam: &model.TeamOddsInfo{
				Name:   away.Name,
				Spread: away.Point,
			},
		})
	}

	return result, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
