package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"apollo/graph/model"
	"context"
)

// GetLeagueSeasonsByID is the resolver for the GetLeagueSeasonsById field.
func (r *queryResolver) GetLeagueSeasonsByID(ctx context.Context, leagueID string) ([]*model.Season, error) {
	rows, err := r.DB.Query(ctx, `
        SELECT s.id, s.year_start, s.year_end, s.sport
        FROM season s
        INNER JOIN league l ON s.league_id = l.id
        WHERE l.id = $1`, leagueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var seasons []*model.Season
	for rows.Next() {
		var s model.Season
		if err := rows.Scan(&s.ID, &s.YearStart, &s.YearEnd, &s.Sport); err != nil {
			return nil, err
		}
		seasons = append(seasons, &s)
	}

	if rows.Err() != nil {
		return nil, rows.Err()
	}

	return seasons, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
