// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

type Season struct {
	ID        string `json:"id"`
	YearStart string `json:"year_start"`
	YearEnd   string `json:"year_end"`
	Sport     string `json:"sport"`
}
